import { authenticated,privateResponse,sameOrigin } from '@/lib/admin-auth';
import { adminData,baseContent } from '@/lib/cms-admin';
import { readStore,writeStore } from '@/lib/cms-store';
import { contentPath,publishIssues } from '@/lib/cms-types';
import { cmsInput } from '@/lib/cms-validation';
import { BlobPreconditionFailedError } from '@vercel/blob';
import { revalidatePath,revalidateTag } from 'next/cache';
import { randomUUID } from 'node:crypto';
export const dynamic='force-dynamic';
export async function GET(request:Request){if(!await authenticated())return privateResponse({error:'Please sign in.'},401);try{const {store}=await readStore(),id=new URL(request.url).searchParams.get('id');if(id){const r=store.records.find(r=>r.id===id),base=baseContent(id);return r?privateResponse({...r,published:r.scheduled&&Date.parse(r.scheduled.publishedAt||'')<=Date.now()?r.scheduled:r.published}):base?privateResponse({id,revision:0,draft:base,history:[],published:base}):privateResponse({error:'Content not found.'},404);}return privateResponse(adminData(store));}catch{return privateResponse({error:'Content could not be loaded. Please try again.'},503);}}
export async function POST(request:Request){if(!await authenticated())return privateResponse({error:'Please sign in.'},401);if(!sameOrigin(request))return privateResponse({error:'Invalid origin.'},403);try{const raw=await request.text();if(raw.length>200000)return privateResponse({error:'Content is too large.'},413);const data=JSON.parse(raw),actions=['save','publish','unpublish','restore','delete'];if(!actions.includes(data.action))return privateResponse({error:'Unknown action.'},400);const {store,etag}=await readStore();let record=store.records.find(r=>r.id===data.content?.id);const previous=record;
 if(record&&record.revision!==data.revision)return privateResponse({error:'This content changed in another editor. Reload before saving.'},409);
 const parsed=cmsInput.safeParse(data.action==='restore'?record?.history[data.historyIndex]?.content:data.content);if(!parsed.success)return privateResponse({error:parsed.error.issues[0]?.message||'Invalid content.'},400);const c=parsed.data;if(!adminData(store).authors.some(a=>a.slug===c.authorSlug))return privateResponse({error:"Choose a published author."},400);
 const base=baseContent(c.id);if(base&&(base.kind!==c.kind||base.slug!==c.slug)||record&&(record.draft.slug!==c.slug||record.draft.kind!==c.kind))return privateResponse({error:'Published URLs and content types stay fixed. Create a new entry for a different URL.'},400);
 if(!record&&!base&&store.records.some(r=>contentPath(r.draft)===contentPath(c))||!base&&!record&&baseContent(contentPath(c)))return privateResponse({error:'That URL is already used. Open the existing entry instead.'},409);
 if(data.action==='publish'){const issues=publishIssues(c);if(issues.length)return privateResponse({error:issues.join(' ')},400);if(data.publishAt&&(!Number.isFinite(Date.parse(data.publishAt))||Date.parse(data.publishAt)<Date.now()-60000))return privateResponse({error:'Choose a future publishing time.'},400);}
 const now=new Date().toISOString();if(!record){record={id:base?.id||randomUUID(),draft:{...c,id:base?.id||''},published:base,revision:0,updatedAt:now,history:[]};record.draft.id=record.id;store.records.push(record);}const id=record.id,content={...c,id,updatedAt:now};if(previous)record.history=[{at:previous.updatedAt,content:previous.draft},...previous.history].slice(0,10);record.draft=content;record.updatedAt=now;record.revision++;
 if(data.action==='publish'){if(data.publishAt){record.scheduled={...content,publishedAt:data.publishAt,updatedAt:data.publishAt};record.draft=record.scheduled;}else{record.published={...content,publishedAt:record.published?.publishedAt||now};record.scheduled=undefined;record.draft=record.published;}record.hidden=false;}
 if(data.action==='unpublish'){record.hidden=true;record.published=undefined;record.scheduled=undefined;}
 if(data.action==='delete'){if(record.published||record.scheduled||base)return privateResponse({error:'Unpublish existing content first. Only new unpublished drafts can be deleted.'},400);store.records=store.records.filter(r=>r.id!==id);}
 store.revision++;store.activity=[{at:now,title:c.title,action:data.action==='publish'&&data.publishAt?'scheduled':data.action},...store.activity].slice(0,200);await writeStore(store,etag);revalidateTag('cms',{expire:0});for(const path of [contentPath(c),'/', '/tools','/guides','/compare','/alternatives','/community','/authors','/services','/everything-ai','/api/ai-news','/sitemap.xml','/rss.xml','/atom.xml','/feed.json','/llms.txt','/llms-full.txt', '/categories/'+c.category])revalidatePath(path);return privateResponse({ok:true,record,data:adminData(store)});
 }catch(e){if(e instanceof BlobPreconditionFailedError)return privateResponse({error:'Another editor saved at the same time. Reload and try again.'},409);return privateResponse({error:'Your changes could not be saved. Your text is still in the editor; please try again.'},503);}}
