import {PageStructuredData} from '@/components/page-structured-data';
import {MotionSymbol} from '@/components/motion-symbol';
import Image from 'next/image';
import Link from '@/components/site-link';
import {ArrowUpRight,Compass,Layers3,ScanLine,Check,MessageCircle} from 'lucide-react';
import {AuthorCards} from '@/components/author-card';
import {pageMetadata} from '@/lib/seo';
import {SITE,tools,categories,guides} from '@/lib/catalog';
export const metadata=pageMetadata({title:'About TruTool — Clearer Choices, Better Tools',description:'Meet the people behind TruTool. Explore our approach to software discovery, practical comparisons, and buying guides for every kind of work.',alternates:{canonical:SITE+'/about'}});
export default function Page(){return <main id="main" className="about-page"><PageStructuredData path="/about"/>
 <section className="about-hero"><div className="shell about-hero-grid"><div className="about-hero-copy"><span className="about-kicker"><span/>THE WHY BEHIND TRUTOOL</span><h1>A world of tools.<br/><em>A clearer way in.</em></h1><p>The next great tool is the one that makes your work better. We help you find it, understand it, and choose with a little more clarity.</p><div className="about-hero-actions"><Link className="button lime" href="/tools">Find your next tool <ArrowUpRight size={18}/></Link><Link className="about-text-link" href="#team">Meet the people <span aria-hidden="true">↓</span></Link></div></div>
 <div className="about-map" aria-label="Discover, compare, and choose with TruTool"><div className="about-map-grid"/><div className="about-orbit orbit-one"/><div className="about-orbit orbit-two"/><div className="about-map-center"><Image src="/identity/trutool-icon-dark.svg" width={370} height={370} alt="TruTool" unoptimized/><span>Your next move.</span></div><div className="about-map-note note-ai"><MotionSymbol kind="sparkles" size={21}/><div><strong>AI & automation</strong><span>A little possibility.</span></div></div><div className="about-map-note note-design"><MotionSymbol kind="design" size={21}/><div><strong>Design & creativity</strong><span>Make the idea real.</span></div></div><div className="about-map-note note-work"><MotionSymbol kind="compass" size={21}/><div><strong>Everyday work</strong><span>Find your flow.</span></div></div><span className="about-map-caption">ONE DIRECTORY. YOUR DIRECTION.</span></div>
 </div></section>
 <div className="shell about-stats" aria-label="TruTool directory at a glance"><div><strong>{tools.length.toLocaleString('en-US')}<span> tools</span></strong><p>A wider world to explore</p></div><div><strong>{categories.length}<span> categories</span></strong><p>Built around different kinds of work</p></div><div><strong>{guides.length}<span> buying guides</span></strong><p>Better questions before you choose</p></div><Link href="/categories">Follow your curiosity <ArrowUpRight size={21}/></Link></div>
 <section className="shell about-purpose"><div><span className="eyebrow">LESS SEARCHING. MORE UNDERSTANDING.</span><h2>Big possibilities.<br/><span>Practical decisions.</span></h2></div><div><p>Software should open doors. But between feature lists, crowded categories, and ambitious promises, choosing can feel like a job of its own.</p><p>TruTool brings the useful details into focus: what a tool helps you do, where it fits, what to question, and how to give it a fair test.</p><Link className="text-link" href="/methodology">See how we research <ArrowUpRight size={17}/></Link></div></section>
 <section className="shell about-path"><div className="about-section-heading"><div><span className="eyebrow">FROM CURIOUS TO CONFIDENT</span><h2>Make your next move.</h2></div><p>Three ways to turn a big directory into a useful decision.</p></div><div className="about-path-grid">{[{icon:Compass,title:'Find your direction.',body:'Start with a task, a category, or a tool you already know. Discover possibilities that fit the work.',href:'/categories',link:'Explore categories',tone:'lime'},{icon:Layers3,title:'See the whole picture.',body:'Compare the same fields side by side: workflow, capabilities, trade-offs, and where to confirm pricing.',href:'/compare',link:'Build a comparison',tone:'lavender'},{icon:ScanLine,title:'Make it your own.',body:'Use a practical buying guide or build a pilot plan. Ask better questions, then test what matters to you.',href:'/diagnostic',link:'Start your diagnostic',tone:'teal'}].map(x=><Link className={'about-path-card '+x.tone} href={x.href} key={x.href}><span className="about-path-icon"><MotionSymbol kind={x.icon===Compass?'compass':x.icon===ScanLine?'scan':'layers'} size={27}/></span><h3>{x.title}</h3><p>{x.body}</p><strong>{x.link}<ArrowUpRight size={19}/></strong></Link>)}</div></section>
 <section id="team" className="about-team"><div className="shell"><div className="about-section-heading"><div><span className="eyebrow">FOUR VOICES. A SHARED POINT OF VIEW.</span><h2>Meet the people<br/>behind the perspective.</h2></div><div><p>Different interests. The same goal: make useful tools easier to understand.</p><Link className="text-link" href="/authors">Explore the editorial team <ArrowUpRight size={17}/></Link></div></div><AuthorCards/></div></section>
 <section className="shell about-principles"><div><span className="eyebrow">WHAT YOU CAN EXPECT</span><h2>A useful point of view.<br/><span>Room for your own.</span></h2><p>Good research should help you think through a decision. Here is what shapes ours.</p><Link className="text-link" href="/editorial-policy">Read our editorial approach <ArrowUpRight size={17}/></Link></div><div className="about-principle-list">{[{title:'The work comes first.',body:'We organize discovery around what you need to achieve, from a creative idea to a team workflow.'},{title:'The source stays visible.',body:'Official vendor links, pricing pages, and practical evaluation questions help you look closer.'},{title:'Fit matters more than hype.',body:'A capability can be useful for one team and unnecessary for another. Trade-offs belong in the conversation.'},{title:'Better with your perspective.',body:'Ask a question, share an experience, or send a supported correction. There is always more to learn.'}].map(x=><div key={x.title}><span><Check size={19}/></span><div><h3>{x.title}</h3><p>{x.body}</p></div></div>)}</div></section>
 <section className="shell about-invite"><div><span className="about-kicker"><MessageCircle size={17}/>YOUR NEXT IDEA STARTS HERE</span><h2>Let’s make a<br/>clearer next move.</h2><p>Have a question, a tool to share, or a perspective we should hear?</p></div><div className="about-invite-actions"><Link className="button lime" href="/contact">Start a conversation <ArrowUpRight size={19}/></Link><Link className="about-text-link" href="/community">Join the conversation <ArrowUpRight size={18}/></Link></div></section>
 </main>}
