'use client';
import {useDeferredValue,useMemo,useState} from 'react';
import {Search,ArrowUpRight,MessageCircle} from 'lucide-react';
import Link from './site-link';
import {Monogram} from './tool-card';
import {HelpfulCount,useHelpfulCounts} from './helpful-vote';
type Question={slug:string;category:string;label:string;question:string;answer:string;helpful:number;tools:Array<{slug:string;name:string;initial:string}>};
export function CommunityQuestions({questions}:{questions:Question[]}){
 const [query,setQuery]=useState(''),[category,setCategory]=useState(''),[page,setPage]=useState(1),deferred=useDeferredValue(query);
 const topics=useMemo(()=>[...new Map(questions.map(q=>[q.category,{slug:q.category,label:q.label}])).values()].sort((a,b)=>a.label.localeCompare(b.label)),[questions]);
 const results=useMemo(()=>questions.filter(q=>(!category||q.category===category)&&(!deferred.trim()||(q.question+' '+q.answer+' '+q.label+' '+q.tools.map(t=>t.name).join(' ')).toLowerCase().includes(deferred.trim().toLowerCase()))),[questions,category,deferred]);
 const pages=Math.max(1,Math.ceil(results.length/12)),current=Math.min(page,pages),visible=results.slice((current-1)*12,current*12),counts=useHelpfulCounts(visible.map(q=>q.slug));
 return <section id="questions" className="community-questions"><div className="section-heading"><div><span className="eyebrow">BETTER QUESTIONS. BETTER CHOICES.</span><h2>Good questions. Useful answers.</h2><p>Practical answers for choosing tools and making them work.</p></div><span className="community-result-count" aria-live="polite">{results.length} {results.length===1?'question':'questions'}</span></div><div className="community-search"><label><Search size={19}/><span className="sr-only">Search community questions</span><input value={query} onChange={e=>{setQuery(e.target.value);setPage(1)}} placeholder="Try AI, team chat, pricing, or a tool name…"/></label><select aria-label="Community category" value={category} onChange={e=>{setCategory(e.target.value);setPage(1)}}><option value="">All topics</option>{topics.map(t=><option value={t.slug} key={t.slug}>{t.label}</option>)}</select></div><div className="question-grid">{visible.map(q=><article className="question-card" key={q.slug}><div className="question-card-top"><span>{q.label}</span><MessageCircle size={16}/></div><h3><Link href={'/community/'+q.slug}>{q.question}</Link></h3><p className="question-excerpt">{q.answer}</p><div className="question-tools">{q.tools.map(t=><Link key={t.slug} href={'/tools/'+t.slug}><Monogram tool={t}/><span>{t.name}</span></Link>)}</div><div className="question-card-bottom"><HelpfulCount count={counts[q.slug]?.count??q.helpful}/><Link className="question-read-answer" aria-label={'Read answer: '+q.question} href={'/community/'+q.slug}>Read answer <ArrowUpRight size={14}/></Link></div></article>)}</div>{!results.length&&<div className="empty-state"><h3>No matching question yet.</h3><p>Try a broader task or start a new conversation.</p><button className="button dark" onClick={()=>{setQuery('');setCategory('');setPage(1)}}>Reset topics</button></div>}{pages>1&&<nav className="directory-pagination" aria-label="Community question pages"><button className="chip" disabled={current===1} onClick={()=>setPage(current-1)}>Previous</button><span>Page {current} of {pages}</span><button className="chip" disabled={current===pages} onClick={()=>setPage(current+1)}>Next</button></nav>}</section>;
}
