'use client';
import {useState} from 'react';
import {MessageCircle,Send,CheckCircle2} from 'lucide-react';
import Link from './site-link';
type AnswerContext={slug:string;question:string;category:string};
export function CommunityCompose({categories,answer}:{categories:{slug:string;label:string}[];answer?:AnswerContext}){
 const [mode,setMode]=useState<'question'|'perspective'>(answer?'perspective':'question'),[status,setStatus]=useState<'idle'|'sending'|'success'|'error'>('idle'),[error,setError]=useState(''),[reference,setReference]=useState(''),[submitted,setSubmitted]=useState('');
 async function submit(event:React.FormEvent<HTMLFormElement>){event.preventDefault();const form=event.currentTarget,data=new FormData(form);setStatus('sending');setError('');try{const response=await fetch('/api/community',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({kind:mode,name:data.get('name'),email:data.get('email'),category:data.get('category'),question:data.get('question'),message:data.get('message'),answerSlug:mode==='perspective'?answer?.slug:undefined,consent:data.get('consent')==='on',website:data.get('website')})}),result=await response.json();if(!response.ok)throw new Error(result.error||'Please try again.');setReference(result.id.slice(0,8));setSubmitted(mode==='question'?String(data.get('question')):answer?.question||'Your experience');setStatus('success');form.reset();}catch(e){setError(e instanceof Error?e.message:'We could not save your submission. Please try again.');setStatus('error');}}
 if(status==='success')return <div className="community-compose-success" role="status"><CheckCircle2 size={28}/><h3>{mode==='question'?'Your question is in.':'Thanks for sharing your perspective.'}</h3><p>{submitted}</p><small>Saved for editorial review · Reference {reference}</small><p>We review submissions before publishing. Your email stays private.</p><button type="button" className="button dark" onClick={()=>{setStatus('idle');setMode('question');setError('')}}>Ask another question</button></div>;
 return <form className="community-compose" onSubmit={submit}><div className="community-compose-tabs" aria-label="Submission type"><button type="button" aria-pressed={mode==='question'} onClick={()=>{setMode('question');setError('')}}>Ask a question</button><button type="button" aria-pressed={mode==='perspective'} onClick={()=>{setMode('perspective');setError('')}}>Share an experience</button></div>{mode==='perspective'&&answer&&<div className="community-compose-context"><MessageCircle size={16}/><div><span>YOUR PERSPECTIVE ON</span><Link href={'/community/'+answer.slug}>{answer.question}</Link></div></div>}<div className="compose-row"><label htmlFor="community-name">Display name<input id="community-name" name="name" autoComplete="name" required minLength={2} maxLength={80} placeholder="How you’d like to appear"/></label><label htmlFor="community-email">Email <span>(optional, kept private)</span><input id="community-email" name="email" type="email" autoComplete="email" maxLength={254} placeholder="you@company.com"/></label></div><label htmlFor="community-topic">Topic<select id="community-topic" name="category" defaultValue={answer?.category||'other'}><option value="other">General tool question</option>{categories.map(c=><option value={c.slug} key={c.slug}>{c.label}</option>)}</select></label>{mode==='question'&&<label htmlFor="community-question">Your question<input id="community-question" name="question" required minLength={12} maxLength={180} placeholder="For example: Which tool fits a five-person design team?"/></label>}<label htmlFor="community-message">{mode==='question'?'A little context':'Your experience'} {mode==='question'&&<span>(optional)</span>}<textarea id="community-message" name="message" required={mode==='perspective'} minLength={mode==='perspective'?20:undefined} maxLength={1800} rows={3} placeholder={mode==='question'?'What are you trying to do? Mention the tools, budget, or team size that matter.':'What worked, what didn’t, and what would you tell someone trying the same task?'}/></label><div className="form-honeypot" aria-hidden="true"><label htmlFor="community-website">Leave this empty<input id="community-website" name="website" tabIndex={-1} autoComplete="off"/></label></div><label className="community-compose-consent"><input type="checkbox" name="consent" required/><span>I’m happy for my display name and submission to be published after review. <Link href="/privacy">Privacy policy</Link></span></label>{status==='error'&&<p className="form-error" role="alert">{error}</p>}<div className="compose-submit"><button className="button dark" type="submit" disabled={status==='sending'}><Send size={15}/>{status==='sending'?'Sending…':mode==='question'?'Submit your question':'Share your perspective'}</button><small>Reviewed before publication.</small></div></form>;
}
