'use client';
import {useState} from 'react';
const stories=[
 {name:'Jake Clarke',role:'Product Marketing & Ops Lead · Equals',tool:'Notion',quote:'Our product documentation used to require periodic clean-ups. With Custom Agents, it maintains itself.',source:'https://www.notion.com/customers/equals'},
 {name:'Robert Kim',role:'Engineering Manager · Brex',tool:'Linear',quote:'Engineers picked up Linear quickly with no formal training.',source:'https://linear.app/customers/brex'},
 {name:'Andrew von Rosenbach',role:'Cohere',tool:'Linear',quote:'Linear strikes a nice balance of being very easy to onboard a team to',source:'https://linear.app/customers/cohere'},
 {name:'Anoop Narang',role:'Head of Digital Workplace and Solutions · Rivian',tool:'Slack',quote:'Slack is an important tool at Rivian. It brings people together to innovate and collaborate',source:'https://slack.com/customer-stories/rivian-story'}
];
export function CommunityBanner(){const [paused,setPaused]=useState(false);return <section className={'community-section '+(paused?'paused':'')}><div className="shell section-heading"><div><span className="eyebrow">FROM THE COMMUNITY</span><h2>Real people. Real workflows.</h2><p>Different teams, different ways to make work better.</p></div><button className="chip" onClick={()=>setPaused(p=>!p)} aria-pressed={paused}>{paused?'Play stories':'Pause stories'}</button></div><div className="community-window"><div className="community-track">{[0,1].map(copy=><div className="community-set" key={copy} aria-hidden={copy===1?true:undefined}>{stories.map(s=><a className="community-card" key={s.name} href={s.source} target="_blank" rel="noopener noreferrer" tabIndex={copy===1?-1:0}><span className="community-product">{s.tool} <span>Customer story ↗</span></span><blockquote>“{s.quote}”</blockquote><div className="community-person"><span className="avatar">{s.name.split(' ').map(x=>x[0]).slice(0,2).join('')}</span><div><strong>{s.name}</strong><small>{s.role}</small></div></div></a>)}</div>)}</div></div><p className="shell community-scope">Excerpts from vendor-published customer stories; these are not TruTool-submitted reviews. Open a card to read its source.</p></section>}
