'use client';
import {useDeferredValue,useMemo,useState} from 'react';
import {Search,ArrowUpRight,MessageCircle} from 'lucide-react';
import Link from './site-link';
import {Monogram} from './tool-card';
type Question={id:string;category:string;label:string;question:string;answer:string;tools:Array<{slug:string;name:string;initial:string}>};
export function CommunityQuestions({questions}:{questions:Question[]}){
 const [query,setQuery]=useState(''),[category,setCategory]=useState(''),[page,setPage]=useState(1),deferred=useDeferredValue(query);
 const results=useMemo(()=>questions.filter(q=>(!category||q.category===category)&&(!deferred.trim()||(q.question+' '+q.answer+' '+q.label+' '+q.tools.map(t=>t.name).join(' ')).toLowerCase().includes(deferred.trim().toLowerCase()))),[questions,category,deferred]);
 const pages=Math.max(1,Math.ceil(results.length/12)),current=Math.min(page,pages);
 return <section id="questions" className="community-questions"><div className="section-heading"><div><span className="eyebrow">BETTER QUESTIONS. BETTER CHOICES.</span><h2>Find your next conversation.</h2><p>Editorial discussion starters with practical answers. Bring your own experience.</p></div><span className="community-result-count" aria-live="polite">{results.length} questions</span></div><div className="community-search"><label><Search size={19}/><span className="sr-only">Search community questions</span><input value={query} onChange={e=>{setQuery(e.target.value);setPage(1)}} placeholder="Try AI, team chat, pricing, or a tool name…"/></label><select aria-label="Community category" value={category} onChange={e=>{setCategory(e.target.value);setPage(1)}}><option value="">All topics</option>{questions.map(q=><option value={q.category} key={q.id}>{q.label}</option>)}</select></div><div className="question-grid">{results.slice((current-1)*12,current*12).map(q=><article className="question-card" key={q.id}><div className="question-card-top"><span>{q.label}</span><MessageCircle size={18}/></div><h3>{q.question}</h3><details><summary>Read the starting point <span aria-hidden="true">+</span></summary><p>{q.answer}</p><Link className="text-link" href={'/contact?message='+encodeURIComponent('Community question: '+q.question+'\n\nMy experience: ')}>Share your perspective <ArrowUpRight size={14}/></Link></details><div className="question-tools">{q.tools.map(t=><Link key={t.slug} href={'/tools/'+t.slug}><Monogram tool={t}/><span>{t.name}</span></Link>)}</div><Link className="question-category" href={'/categories/'+q.category}>Explore this topic <ArrowUpRight size={14}/></Link></article>)}</div>{!results.length&&<div className="empty-state"><h3>No matching question yet.</h3><p>Try a broader task or start a new conversation.</p><button className="button dark" onClick={()=>{setQuery('');setCategory('');setPage(1)}}>Reset topics</button></div>}{pages>1&&<nav className="directory-pagination" aria-label="Community question pages"><button className="chip" disabled={current===1} onClick={()=>setPage(current-1)}>Previous</button><span>Page {current} of {pages}</span><button className="chip" disabled={current===pages} onClick={()=>setPage(current+1)}>Next</button></nav>}</section>;
}
