
'use client';
import {useState} from 'react';
import Link from '@/components/site-link';
import {Checkbox} from '@/components/ui/checkbox';
import type {CategoryOption,ToolResults} from '@/lib/catalog-client';
import {useToolResults} from './use-tool-results';
import {Monogram} from './tool-card';
export function ComparePicker({initial=[],seed,categories}:{initial?:Array<{slug:string;name:string}>;seed:ToolResults;categories:CategoryOption[]}){
 const [selected,setSelected]=useState(initial),[category,setCategory]=useState(seed.category),[page,setPage]=useState(1);
 const [query,setQuery]=useState('');
 const {data,busy,error,retry}=useToolResults(seed,query,category,'relevance',page,50);
 const toggle=(tool:{slug:string;name:string},checked:boolean)=>setSelected(s=>checked?s.some(x=>x.slug===tool.slug)?s:s.length<3?[...s,tool]:s:s.filter(x=>x.slug!==tool.slug));
 return <section aria-label="Build your comparison"><div className="compare-instructions"><span>1. Choose a category</span><span>2. Select 2–3 tools</span><span>3. Open your comparison</span></div><div className="filter-bar universal-filter"><select aria-label="Comparison category" value={category} onChange={e=>{setCategory(e.target.value);setSelected([]);setQuery('');setPage(1)}}>{categories.map(c=><option key={c.slug} value={c.slug}>{c.short}</option>)}</select><input aria-label="Search tools to compare" value={query} onChange={e=>{setQuery(e.target.value);setPage(1)}} placeholder="Search this category…"/></div>{error&&<p role="alert">{error} <button className="chip" onClick={retry}>Retry search</button></p>}<div className="select-list" aria-busy={busy}>{(busy||error?[]:data.items).map(t=><label className={'select-item '+(selected.some(x=>x.slug===t.slug)?'is-selected':'')} key={t.slug}><Monogram tool={t}/><span>{t.name}</span><Checkbox aria-label={'Select '+t.name} checked={selected.some(x=>x.slug===t.slug)} disabled={busy||(selected.length===3&&!selected.some(x=>x.slug===t.slug))} onCheckedChange={v=>toggle(t,v===true)}/></label>)}</div><nav className="directory-pagination" aria-label="Comparison choices"><span aria-live="polite">{busy?'Updating choices…':data.total+' tools'}</span>{data.pages>1&&<><button className="chip" disabled={busy||data.page===1} onClick={()=>setPage(data.page-1)}>Previous</button><span>{data.page} / {data.pages}</span><button className="chip" disabled={busy||data.page===data.pages} onClick={()=>setPage(data.page+1)}>Next</button></>}</nav><div className="compare-builder-actions"><div aria-live="polite"><strong>{selected.length} of 3 selected</strong><p>{selected.length===0?'Select at least two tools above.':selected.length===1?'Choose one more tool to compare.':selected.map(s=>s.name).join(' · ')}</p></div><div>{selected.length>=2?<Link className="button dark" href={'/compare?tools='+selected.map(s=>s.slug).join(',')}>Compare {selected.length} platforms</Link>:<button type="button" disabled className="button dark">Compare platforms</button>}{selected.length>0&&<button type="button" className="chip" onClick={()=>setSelected([])}>Clear selection</button>}</div></div></section>
}
