import {Table,TableHeader,TableBody,TableRow,TableHead,TableCell} from '@/components/ui/table';
import {Tool,categoryOf} from '@/lib/catalog';
import {pricingFor} from '@/lib/pricing';
import {ratingFor} from '@/lib/reviews';
import {RatingSummary} from './rating-summary';
import {Monogram} from './tool-card';
import Link from '@/components/site-link';
export function CompareTable({items}:{items:Tool[]}){
 const rows=[{label:'What it does',get:(t:Tool)=>t.summary},{label:'Potential fit',get:(t:Tool)=>t.fit},{label:'Category',get:(t:Tool)=><Link className="comparison-category" href={'/categories/'+t.category}>{categoryOf(t.category).short}</Link>},{label:'Key capabilities',get:(t:Tool)=><ul className="comparison-capabilities">{t.features.map(f=><li key={f}>{f}</li>)}</ul>},{label:'Look closer',get:(t:Tool)=><div className="comparison-caution">{t.caution}</div>},{label:'Pricing & plans',get:(t:Tool)=><div className="comparison-pricing"><span>{t.pricing}</span><a className="text-link" href={pricingFor(t).url} target="_blank" rel="noopener noreferrer">{pricingFor(t).label}</a></div>},{label:'Community rating',get:(t:Tool)=><RatingSummary rating={ratingFor('tool',t.slug)}/>},{label:'Vendor source',get:(t:Tool)=><a className="text-link" href={t.url} target="_blank" rel="noopener noreferrer">Official vendor website ↗</a>},{label:'Explore',get:(t:Tool)=><Link className="button dark" href={'/tools/'+t.slug}>Read the profile ↗</Link>}];
 return <section className="comparison-workspace" aria-label="Tool comparison"><div className="comparison-snapshot" style={{gridTemplateColumns:`repeat(${items.length},minmax(0,1fr))`}}>{items.map((t,i)=><article key={t.slug} className={'comparison-summary summary-'+i}><div className="comparison-summary-heading"><Monogram tool={t}/><div><Link href={'/tools/'+t.slug}><h2>{t.name}</h2></Link><RatingSummary rating={ratingFor('tool',t.slug)} compact/></div></div><span className="eyebrow">POTENTIAL FIT</span><p>{t.fit}</p><div className="comparison-tags">{t.features.slice(0,3).map(f=><span key={f}>{f}</span>)}</div><a className="text-link" href={pricingFor(t).url} target="_blank" rel="noopener noreferrer">{pricingFor(t).label}</a></article>)}</div><div className="comparison-reading-key"><strong>Compare the work, then the plan.</strong><span>Capabilities · fit · trade-offs · costs</span></div><div className="table-wrap"><Table className="compare-table"><caption className="sr-only">Compare {items.map(t=>t.name).join(', ')} by fit, capabilities, pricing, and published community ratings.</caption><TableHeader><TableRow><TableHead scope="col">Compare by</TableHead>{items.map(t=><TableHead scope="col" key={t.slug}><div className="comparison-table-brand"><Monogram tool={t}/><div><strong>{t.name}</strong><RatingSummary rating={ratingFor('tool',t.slug)} compact/></div></div></TableHead>)}</TableRow></TableHeader><TableBody>{rows.map(r=><TableRow key={r.label}><TableHead scope="row">{r.label}</TableHead>{items.map(t=><TableCell key={t.slug}>{r.get(t)}</TableCell>)}</TableRow>)}</TableBody></Table></div><div className="comparison-evidence"><span>01 · Define one task</span><span>02 · Test the same inputs</span><span>03 · Check cost and export</span><Link href="/diagnostic">Build your pilot plan ↗</Link></div></section>;
}
