'use client';
import {useState} from 'react';
import Link from '@/components/site-link';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Textarea} from '@/components/ui/textarea';
import {Select,SelectContent,SelectItem,SelectTrigger,SelectValue} from '@/components/ui/select';
export function ContactForm(){const [topic,setTopic]=useState('conversation'),[status,setStatus]=useState<'idle'|'sending'|'success'|'error'>('idle'),[error,setError]=useState(''),[reference,setReference]=useState('');
 async function submit(event:React.FormEvent<HTMLFormElement>){event.preventDefault();const form=event.currentTarget,data=new FormData(form);setStatus('sending');setError('');try{const response=await fetch('/api/contact',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name:data.get('name'),email:data.get('email'),topic,message:data.get('message'),website:data.get('website')})});const result=await response.json() as {error?:string;id:string};if(!response.ok)throw new Error(result.error||'Please try again.');setReference(result.id.slice(0,8));setStatus('success');form.reset();}catch(e){setError(e instanceof Error?e.message:'We could not send your message. Please try again.');setStatus('error');}}
 if(status==='success')return <div className="contact-confirmation" role="status"><span className="eyebrow">MESSAGE RECEIVED</span><h2>Your conversation has started.</h2><p>Your message has been saved to the TruTool team inbox. Reference: {reference}.</p><Button className="button dark" onClick={()=>setStatus('idle')}>Send another message</Button><Link className="text-link" href="/tools">Continue exploring tools</Link></div>;
 return <form className="contact-form" onSubmit={submit}><div className="form-row"><div><label htmlFor="contact-name">Your name</label><Input id="contact-name" name="name" autoComplete="name" required minLength={2} maxLength={100} placeholder="Your name"/></div><div><label htmlFor="contact-email">Email address</label><Input type="email" id="contact-email" name="email" autoComplete="email" required maxLength={254} placeholder="you@company.com"/></div></div><div><label id="topic-label">What would you like to discuss?</label><Select value={topic} onValueChange={setTopic}><SelectTrigger aria-labelledby="topic-label"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="conversation">Start a conversation</SelectItem><SelectItem value="correction">Report a correction</SelectItem><SelectItem value="suggestion">Suggest a tool</SelectItem><SelectItem value="privacy">Privacy question</SelectItem></SelectContent></Select></div><div><label htmlFor="contact-message">Your message</label><Textarea id="contact-message" name="message" required minLength={20} maxLength={4000} rows={6} placeholder="Tell us about your product, question, or what you would like to improve."/></div><div className="form-honeypot" aria-hidden="true"><label htmlFor="company-site">Leave this empty</label><input id="company-site" name="website" tabIndex={-1} autoComplete="off"/></div><p className="form-note">Your details are used to handle this enquiry. Read our <Link href="/privacy">privacy policy</Link>. Please keep confidential information out of your message.</p>{status==='error'&&<p className="form-error" role="alert">{error}</p>}<Button type="submit" disabled={status==='sending'} className="button dark">{status==='sending'?'Sending your message…':'Start a conversation'}</Button></form>}
