'use client';
import {useState,useRef,useId} from 'react';
import {Search,TrendingUp} from 'lucide-react';
import Link from './site-link';
import type {Tool} from '@/lib/catalog';
const topics=['AI research assistants','Meeting notes','Remove image backgrounds','Project management','No-code app builders','SEO tools','Local listings management','RFP response software'];
export function DiscoverySearch({value,onChange,name='q',placeholder='What do you need a tool for?',hero=false}:{value?:string;onChange?:(v:string)=>void;name?:string;placeholder?:string;hero?:boolean}){
 const [text,setText]=useState(value||''),[open,setOpen]=useState(false),[hits,setHits]=useState<Tool[]>([]),[active,setActive]=useState(-1),[loading,setLoading]=useState(false);const input=useRef<HTMLInputElement>(null),request=useRef(0),id=useId();const q=value===undefined?text:value;
 async function suggest(next:string){const n=++request.current;if(!next.trim()){setHits([]);setLoading(false);return;}setLoading(true);try{const {searchTools}=await import('@/lib/search');if(n===request.current){setHits(searchTools(next).slice(0,6));setLoading(false)}}catch{if(n===request.current){setHits([]);setLoading(false)}}}
 function update(v:string){setText(v);onChange?.(v);setActive(-1);void suggest(v);}
 return <div className={'discovery-search '+(hero?'discovery-search-hero':'')} onBlur={e=>{if(!e.currentTarget.contains(e.relatedTarget as Node))setOpen(false)}}><div className="discovery-input"><Search size={22}/><input ref={input} name={name} type="search" value={q} placeholder={placeholder} aria-label={hero?'Search all tools':'Search directory'} role="combobox" aria-autocomplete="list" aria-expanded={open} aria-controls={id} aria-activedescendant={active>=0?id+'-'+active:undefined} autoComplete="off" onFocus={()=>{setOpen(true);void suggest(q)}} onChange={e=>{update(e.target.value);setOpen(true)}} onKeyDown={e=>{const count=q.trim()?hits.length:topics.length;if(e.key==='Escape'){setOpen(false);setActive(-1)}if(e.key==='ArrowDown'){e.preventDefault();setOpen(true);setActive(a=>Math.min(count-1,a+1))}if(e.key==='ArrowUp'){e.preventDefault();setActive(a=>Math.max(-1,a-1))}if(e.key==='Enter'&&active>=0){const anchor=document.getElementById(id+'-'+active) as HTMLAnchorElement|null;if(anchor){e.preventDefault();anchor.click();setOpen(false)}}}}/>{hero&&<button type="submit" aria-label="Find tools">Find tools</button>}</div>{open&&<div className="search-suggestions" id={id} role="listbox" aria-label={q.trim()?'Suggested tools':'Trending searches'}><div className="suggestion-heading">{q.trim()?'MATCHING TOOLS':'TRENDING SEARCHES'}<span>{q.trim()?'Names, tasks, and categories':'Explore this week’s discovery topics'}</span></div>{q.trim()?loading?<p className="suggestion-empty" role="status">Finding relevant tools…</p>:hits.length?hits.map((t,i)=><Link role="option" aria-selected={active===i} id={id+'-'+i} className={active===i?'active':''} key={t.slug} href={'/tools/'+t.slug} onPointerDown={e=>e.preventDefault()} onClick={()=>setOpen(false)}><Search size={16}/><div><strong>{t.name}</strong><small>{t.summary}</small></div></Link>):<p className="suggestion-empty">Try a broader task or category. We’ll help you narrow it down.</p>:topics.map((topic,i)=><Link role="option" aria-selected={active===i} id={id+'-'+i} className={active===i?'active':''} key={topic} href={'/tools?q='+encodeURIComponent(topic)} onPointerDown={e=>e.preventDefault()} onClick={()=>setOpen(false)}><TrendingUp size={17}/><strong>{topic}</strong></Link>)}{q.trim()&&<Link className="all-search-results" href={'/tools?q='+encodeURIComponent(q)} onPointerDown={e=>e.preventDefault()}>See all results for “{q}”</Link>}</div>}</div>
}
