import {ratingFor} from '@/lib/reviews';
import {RatingSummary} from './rating-summary';
import Image from 'next/image';
import {ArrowUpRight} from 'lucide-react';
import Link from '@/components/site-link';
import {categoryOf,guides} from '@/lib/catalog';
export const coverFor=(category:string)=>'/covers/'+(['local-listings','rfp-software','communication','edtech'].includes(category)?category:['design','ai-image','no-code'].includes(category)?'creative-work':['marketing','seo','crm'].includes(category)?'marketing-work':'ai-work')+'.webp';
export const coverAlt=(category:string)=>({'local-listings':'Location markers and a city map representing local business visibility','rfp-software':'Connected documents representing an RFP knowledge library','communication':'Connected conversations representing team communication','edtech':'Books and a study workspace representing professional learning'}[category]||(['design','ai-image','no-code'].includes(category)?'Creative design materials and a vector canvas in lime, navy, and lavender':['marketing','seo','crm'].includes(category)?'A campaign target, magnifying glass, and translucent growth bars':'Connected knowledge cards and a luminous lime intelligence orb'));
export function GuideCard({guide:g}:{guide:typeof guides[number]}){return <Link className="guide-card" href={'/guides/'+g.slug}><div className="guide-art"><Image src={coverFor(g.category)} alt={coverAlt(g.category)} width={800} height={500} sizes="(max-width: 520px) calc(100vw - 40px), (max-width: 900px) 46vw, (max-width: 1399px) 30vw, 23vw"/></div><div className="guide-card-copy"><span className="eyebrow">{categoryOf(g.category).short}</span><h3>{g.title}</h3><span className="read-label">By Yash · Buying checklist</span><RatingSummary rating={ratingFor('guide',g.slug)} compact/><span className="guide-read">Read the guide <ArrowUpRight size={17}/></span></div></Link>}
