'use client';
import {pilotCriteria,pilotScore,type PilotScores} from '@/lib/diagnostic';
import {Monogram} from './tool-card';
import type {Tool} from '@/lib/catalog';
export function PilotScorecard({tools,scores,onChange}:{tools:Tool[];scores:PilotScores;onChange:(value:PilotScores)=>void}){
 const complete=tools.map(tool=>({tool,score:pilotScore(scores[tool.slug]||{})})).filter(x=>x.score!==null).sort((a,b)=>b.score!-a.score!);
 const leaders=complete.filter(x=>x.score===complete[0]?.score);
 return <section className="pilot-scorecard"><span className="eyebrow">YOUR EVIDENCE, SIDE BY SIDE</span><h3>Turn the pilot into a decision.</h3><p>{tools.length?'Score each option after testing the same task.':'Select 2–3 tools in Your shortlist to build your scorecard.'} Use 1 for poor, 3 for acceptable, and 5 for excellent. Quality carries twice the weight.</p>{tools.length>0&&<><div className="scorecard-scroll"><table><caption className="sr-only">Your pilot scores from one to five</caption><thead><tr><th scope="col">Tool</th>{pilotCriteria.map(c=><th scope="col" key={c.id}>{c.label}<small>Weight {c.weight}</small></th>)}<th scope="col">Weighted result</th></tr></thead><tbody>{tools.map(tool=>{const score=pilotScore(scores[tool.slug]||{});return <tr key={tool.slug}><th scope="row"><div><Monogram tool={tool}/><span>{tool.name}</span></div></th>{pilotCriteria.map(c=><td key={c.id}><select aria-label={tool.name+' '+c.label} value={scores[tool.slug]?.[c.id]||''} onChange={e=>{const row={...scores[tool.slug]};if(e.target.value)row[c.id]=Number(e.target.value);else delete row[c.id];onChange({...scores,[tool.slug]:row})}}><option value="">Not tested</option>{[1,2,3,4,5].map(n=><option value={n} key={n}>{n} / 5</option>)}</select></td>)}<td><strong>{score===null?'Awaiting evidence':score.toFixed(1)+' / 5'}</strong></td></tr>})}</tbody></table></div><div className="scorecard-insight" role="status">{complete.length<2?'Complete every criterion for at least two tools to compare your results.':leaders.length>1?leaders.map(x=>x.tool.name).join(' and ')+' are tied in your pilot. Use the unresolved requirements to choose.':leaders[0].tool.name+' leads your completed pilot scores. Confirm its costs and any must-have requirements before committing.'}</div><button type="button" className="text-link" onClick={()=>onChange({})}>Reset my scores</button></>}</section>;
}
