import {MotionSymbol,categorySymbol} from './motion-symbol';
import {Navigation} from './navigation';
import {categoryCounts} from '@/lib/catalog';
import Link from '@/components/site-link';
import {Brand,FooterBrand} from './brand';
import {MotionVisibility} from './motion-visibility';
import {categories} from '@/lib/catalog';
const categoryDotColors=['#8b5cf6','#f97316','#06b6d4','#eab308','#ec4899','#10b981','#3b82f6','#ef4444'];
export function Header(){return <header className="site-header"><div className="shell nav"><Brand/><Navigation categories={categories.map((c,i)=>({slug:c.slug,short:c.short,name:c.name,count:categoryCounts[c.slug],color:categoryDotColors[i%categoryDotColors.length]}))}/><div className="nav-actions"><Link className="nav-about" href="/about" aria-label="About TruTool">About TruTool</Link><Link className="button lime nav-submit" href="/list-your-product"><MotionSymbol kind="plus" size={16}/><MotionSymbol kind="plus" size={15}/>List your product</Link></div></div></header>}
export function Footer(){return <footer className="site-footer"><MotionVisibility selector=".site-footer"/><div className="shell footer-grid"><div className="footer-brand"><FooterBrand/><div className="footer-discovery-path" aria-hidden="true"><span><MotionSymbol kind="compass" size={14}/>Discover</span><i/><span><MotionSymbol kind="compare" size={14}/>Compare</span><i/><span><MotionSymbol kind="sparkles" size={14}/>Choose</span></div><p>Clearer choices.<br/>Better tools. Smarter growth.</p><small>Software and learning,<br/>with a clearer point of view.</small><Link className="footer-contact" href="/contact"><MotionSymbol kind="conversation" size={16}/>Start a conversation</Link></div><div><h3>Explore</h3><Link href="/tools"><MotionSymbol kind="compass" size={15}/>All tools</Link><Link href="/everything-ai"><MotionSymbol kind="sparkles" size={15}/>Everything AI</Link><Link href="/categories"><MotionSymbol kind="layers" size={15}/>Categories</Link><Link href="/compare"><MotionSymbol kind="compare" size={15}/>Comparisons</Link><Link href="/alternatives"><MotionSymbol kind="shuffle" size={15}/>Alternatives</Link><Link href="/guides"><MotionSymbol kind="book" size={15}/>Buying guides</Link><Link href="/community"><MotionSymbol kind="conversation" size={15}/>Community</Link><Link href="/services"><MotionSymbol kind="service" size={15}/>Services directory</Link><Link href="/authors"><MotionSymbol kind="learn" size={15}/>Meet the editorial team</Link></div><div><h3>Find your fit</h3>{categories.filter(c=>['ai','productivity','design','marketing','developer-tools','local-listings','rfp-software','edtech'].includes(c.slug)).map(c=><Link key={c.slug} href={'/categories/'+c.slug}><MotionSymbol kind={categorySymbol(c.slug)} size={15}/>{c.short}</Link>)}</div><div><h3>TruTool</h3><Link href="/about"><MotionSymbol kind="globe" size={15}/>About us</Link><Link href="/contact"><MotionSymbol kind="conversation" size={15}/>Contact</Link><Link href="/list-your-product"><MotionSymbol kind="plus" size={15}/>List your product</Link><Link href="/contact#corrections">Report a correction</Link><Link href="/diagnostic"><MotionSymbol kind="scan" size={15}/>Decision studio</Link></div><div><h3>Trust & transparency</h3><Link href="/methodology">Our methodology</Link><Link href="/sources">Sources & brand credits</Link><Link href="/editorial-policy">Editorial policy</Link><Link href="/privacy">Privacy policy</Link><Link href="/terms">Terms of use</Link><Link href="/cookies">Cookie policy</Link></div></div><div className="shell footer-bottom"><span>© {new Date().getUTCFullYear()} TruTool. All rights reserved.</span><span>Clearer choices. Better tools.</span><div className="footer-utilities"><Link href="/sitemap.xml">Sitemap</Link><Link className="footer-top" href="#main"><MotionSymbol kind="up" size={15}/>Back to top</Link></div></div></footer>}
