'use client';
import {useState,useMemo,useDeferredValue} from 'react';
import Link from '@/components/site-link';
import {Checkbox} from '@/components/ui/checkbox';
import {categories,getTool} from '@/lib/catalog';
import {searchTools} from '@/lib/search';
import {ToolCard} from './tool-card';
import {DiscoverySearch} from './discovery-search';
export function ToolBrowser({initialQuery='',category=''}:{initialQuery?:string;category?:string}){
 const [query,setQuery]=useState(initialQuery),[cat,setCat]=useState(category),[sort,setSort]=useState('relevance'),[selected,setSelected]=useState<string[]>([]),[page,setPage]=useState(1);const deferred=useDeferredValue(query);
 const filtered=useMemo(()=>searchTools(deferred,cat,sort),[deferred,cat,sort]);const size=24,pages=Math.ceil(filtered.length/size),current=Math.min(page,Math.max(pages,1)),shown=filtered.slice((current-1)*size,current*size);
 function changeQuery(q:string){setQuery(q);setPage(1)}
 return <><div className="filter-bar universal-filter"><DiscoverySearch value={query} onChange={changeQuery} placeholder="Search by tool, task, or keyword…"/><select value={cat} aria-label="Filter category" onChange={e=>{setCat(e.target.value);setPage(1);setSelected([])}}><option value="">All {categories.length} categories</option>{categories.map(c=><option key={c.slug} value={c.slug}>{c.short}</option>)}</select><select value={sort} aria-label="Sort tools" onChange={e=>setSort(e.target.value)}><option value="relevance">Best match</option><option value="az">Name: A–Z</option></select></div><div className="discovery-chips">{['ai','productivity','design','marketing','developer-tools','local-listings','rfp-software'].map(slug=>{const c=categories.find(c=>c.slug===slug)!;return <button className={'chip '+(cat===slug?'active':'')} aria-pressed={cat===slug} key={slug} onClick={()=>{setCat(cat===slug?'':slug);setPage(1)}}>{c.short}</button>})}</div><div className="results-meta"><span aria-live="polite">{filtered.length} {filtered.length===1?'tool':'tools'}{query?' for “'+query+'”':''}</span><span>Select 2–3 tools to compare</span></div>{shown.length?<div className="tools-grid" aria-busy={query!==deferred}>{shown.map(t=><div className="browse-card" key={t.slug}><ToolCard tool={t}/><label className="compare-checkbox"><Checkbox checked={selected.includes(t.slug)} disabled={!selected.includes(t.slug)&&selected.length===3} onCheckedChange={v=>setSelected(s=>v?[...s,t.slug]:s.filter(x=>x!==t.slug))} aria-label={'Add '+t.name+' to comparison'}/>Add to comparison</label></div>)}</div>:<div className="empty-state"><h2>No matching tools yet.</h2><p>Try the main task—such as meeting notes, image editing, or customer support—or choose another category.</p><button className="button dark" onClick={()=>{setQuery('');setCat('');setPage(1)}}>Reset search</button><Link className="text-link" href="/list-your-product">Suggest a missing tool</Link></div>}{pages>1&&<nav className="directory-pagination" aria-label="Directory pages"><button className="chip" disabled={current===1} onClick={()=>setPage(current-1)}>Previous</button><span>Page {current} of {pages} · Showing {(current-1)*size+1}–{Math.min(current*size,filtered.length)}</span><button className="chip" disabled={current===pages} onClick={()=>setPage(current+1)}>Next</button></nav>}{selected.length>0&&<div className="compare-tray"><div><strong>{selected.map(s=>getTool(s)!.name).join(' · ')}</strong><p>{selected.length===1?'Choose at least one more tool.':'Your comparison is ready.'}</p></div>{selected.length>=2?<Link className="button lime" href={'/compare?tools='+selected.join(',')}>Compare {selected.length} tools</Link>:<button disabled className="button lime">Compare tools</button>}<button className="chip" onClick={()=>setSelected([])}>Clear</button></div>}</>
}
