import catalogBrands from './catalog-brand-assets.json';
export const brandAssets:Record<string,string>={...catalogBrands,
 "chatgpt-dots":catalogBrands.chatgpt,
 "grok-bot":catalogBrands.grok,
 "openai-agents-sdk":catalogBrands.chatgpt,
 "autogen":"/api/logo?slug=semantic-kernel",
 "qwen-code":"/api/logo?slug=qwen-chat",
  "synup": "/brands/synup.svg",
  "yext": "/brands/yext.svg",
  "uberall": "/brands/uberall.svg",
  "brightlocal": "/brands/brightlocal.svg",
  "birdeye": "/brands/birdeye.webp",
  "semrush-local": "/brands/semrush-local.svg",
  "inventive-ai": "/brands/inventive-ai.png",
  "loopio": "/brands/loopio.svg",
  "responsive": "/brands/responsive.svg",
  "sifthub": "/brands/sifthub.png",
  "autorfp-ai": "/brands/autorfp-ai.svg",
  "qorusdocs": "/brands/qorusdocs.png",
  "slack": "/brands/slack.png",
  "microsoft-teams": "/brands/microsoft-teams.svg",
  "zoom": "/brands/zoom.png",
  "google-meet": "/brands/google-meet.svg",
  "discord": "/brands/discord.png",
  "loom": "/brands/loom.png",
  "staragile": "/brands/staragile.webp",
  "simplilearn": "/brands/simplilearn.svg",
  "coursera": "/brands/coursera.svg",
  "udemy": "/brands/udemy.svg",
  "upgrad": "/brands/upgrad.svg",
  "edx": "/brands/edx.svg"
};
