import coreSourceDates from './core-source-dates.json';
import {additionalGuides} from './guides';
import expanded from './expanded-catalog.json';
export const SITE = process.env.NEXT_PUBLIC_SITE_URL || 'https://trutool-directory.vercel.app';
const coreCategories = [
 {slug:'local-listings',name:'Local listings management',short:'Local marketing',description:'Keep business information accurate across search, maps, and directories.',icon:'MapPin',color:'#e9eaeb',question:'How do I choose local listings management software?',answer:'Start with your locations, priority directories, data ownership, and update workflow. Compare listings distribution, duplicate handling, reviews, reporting, and the work your team still needs to do.'},
 {slug:'rfp-software',name:'RFP & proposal software',short:'RFP & proposals',description:'Find reusable answers, coordinate experts, and build better responses.',icon:'FileText',color:'#e9eaeb',question:'How do I choose RFP response software?',answer:'Test each platform on a real questionnaire with the same source documents. Assess answer traceability, permissions, content freshness, expert review, and export quality before choosing a subscription.'},
 {slug:'communication',name:'Communication tools',short:'Communication',description:'Bring teams together through chat, meetings, and asynchronous video.',icon:'MessagesSquare',color:'#e9eaeb',question:'Which communication tool fits my team?',answer:'Choose around how your team works: persistent chat, live meetings, community channels, or asynchronous recordings. Check guest access, retention, admin controls, and compatibility with your existing workspace.'},
 {slug:'edtech',name:'EdTech & learning platforms',short:'EdTech & learning',description:'Explore live training, self-paced courses, and professional credentials.',icon:'GraduationCap',color:'#e9eaeb',question:'How do I compare professional learning platforms?',answer:'Match the course to your goal, then check live versus self-paced delivery, trainer credentials, projects, total fees, and refund terms. A course completion certificate and a professional certification are different outcomes.'}
];
export const categories=[...coreCategories,...expanded.categories.filter(c=>!coreCategories.some(x=>x.slug===c.slug))];
export type Tool = {slug:string;name:string;category:string;summary:string;fit:string;features:string[];caution:string;url:string;color:string;initial:string;categoryLabel?:string;format:string;pricing:string;keywords?:string;sourceTitle?:string;sourceStatus?:string;sourceChecked?:string|null;updatedAt?:string;sourceUrl?:string};
const make=(slug:string,name:string,category:string,summary:string,fit:string,features:string[],caution:string,url:string,color:string,initial:string,format:string):Tool=>({slug,name,category,summary,fit,features,caution,url,color,initial,format,pricing:'Check current vendor pricing'});
const coreTools:Tool[]=[
make('synup','Synup','local-listings','Manage local business listings, reviews, and location visibility from one platform.','Agencies and multi-location teams managing local presence.',['Listings distribution','Review management','Location reporting'],'Confirm directory coverage and the services included for your locations.','https://synup.com/','#725bf5','S','Software'),
make('yext','Yext','local-listings','Manage business information and digital presence across a network of publishers.','Enterprise teams coordinating location data across markets.',['Business information management','Listings distribution','Local presence tools'],'Confirm the contracted publisher network, integrations, and implementation scope.','https://www.yext.com/','#101826','Y','Software'),
make('uberall','Uberall','local-listings','Coordinate location listings and local customer engagement for multi-location brands.','Brands managing many physical locations and regional teams.',['Listings synchronization','Location data management','Review workflows'],'Check geographic coverage and the modules included in your proposed package.','https://uberall.com/en-us/products/listings','#ed5266','U','Software'),
make('brightlocal','BrightLocal','local-listings','Research local rankings, audit citations, and manage local SEO work.','Local SEO practitioners who need auditing and citation services.',['Local rank tracking','Citation building','Local SEO reporting'],'Citation services and software subscriptions may have separate costs and delivery terms.','https://www.brightlocal.com/','#27836b','B','Software'),
make('birdeye','Birdeye','local-listings','Bring local listings and customer reputation workflows into a multi-location platform.','Brands combining local presence with customer experience operations.',['Local listings','Review management','Customer engagement'],'Compare the exact modules and location-level pricing included in a quote.','https://birdeye.com/','#255bec','b','Software'),
make('semrush-local','Semrush Local','local-listings','Explore local business tools within the wider Semrush marketing ecosystem.','Marketing teams evaluating local visibility tools alongside SEO software.',['Local business tools','Marketing ecosystem','Plan-based access'],'Verify current listings features, regional availability, and whether add-ons are required.','https://www.semrush.com/local-business/start/','#ef7136','S','Software'),
make('inventive-ai','Inventive AI','rfp-software','Use company knowledge to draft RFP and security questionnaire responses with AI.','Presales and proposal teams working across connected knowledge sources.',['AI response drafting','Connected knowledge sources','Content governance'],'Review generated answers and all contractual or security commitments before submission.','https://www.inventive.ai/','#7865ef','i','Software'),
make('loopio','Loopio','rfp-software','Organize reusable response content and coordinate RFP work across a team.','Response teams building repeatable content and review processes.',['Response content management','RFP workflows','Expert collaboration'],'Plan content ownership and review cycles alongside the platform implementation.','https://loopio.com/','#d94b44','L','Software'),
make('responsive','Responsive','rfp-software','Manage response content and proposal workflows through a response management platform.','Teams coordinating responses, knowledge, and contributors at scale.',['Response management','Content library','Team collaboration'],'Test configuration effort and the package needed for your response workflow.','https://www.responsive.io/','#155dbf','R','Software'),
make('sifthub','SiftHub','rfp-software','Find company knowledge and support RFP responses within sales workflows.','Sales and presales teams combining information retrieval with deal work.',['Knowledge search','RFP response support','Deal orchestration'],'Validate source permissions, integration depth, and the handoff to reviewers.','https://www.sifthub.io/','#8c61d8','S','Software'),
make('autorfp-ai','AutoRFP.ai','rfp-software','Apply AI to drafting and coordinating business questionnaire responses.','Teams evaluating an AI-centered workflow for RFP responses.',['AI response generation','RFP collaboration','Questionnaire workflows'],'Pilot source accuracy and final document exports with your own questionnaires.','https://autorfp.ai/','#2976d9','A','Software'),
make('qorusdocs','QorusDocs','rfp-software','Create proposals, pitches, and RFP responses with document automation and AI.','Proposal teams evaluating document-centered selling workflows.',['Proposal automation','RFP response tools','Pitch creation'],'Check template setup and compatibility with your document environment.','https://www.qorusdocs.com/','#2d6862','Q','Software'),
make('slack','Slack','communication','Coordinate conversations and connected work in channels and shared workspaces.','Teams that want persistent messaging and app-connected collaboration.',['Channels','Team messaging','App integrations'],'Compare retention, guest access, and admin features on the selected plan.','https://slack.com/','#67285b','#','Software'),
make('microsoft-teams','Microsoft Teams','communication','Combine chat, meetings, and collaboration in the Microsoft ecosystem.','Organizations already coordinating work in Microsoft 365.',['Team chat','Video meetings','Microsoft ecosystem'],'Confirm regional licensing, meeting limits, and the admin controls you need.','https://www.microsoft.com/en-us/microsoft-teams/group-chat-software','#6258bb','T','Software'),
make('zoom','Zoom','communication','Connect people through online meetings and broader workplace communication tools.','Teams prioritizing video meetings and external collaboration.',['Video meetings','Workplace collaboration','Communication tools'],'Check meeting limits and whether calling or webinar products are separate.','https://www.zoom.com/','#2875ed','z','Software'),
make('google-meet','Google Meet','communication','Run online video meetings within the Google Workspace environment.','Teams using Google Workspace for calendars and shared documents.',['Video conferencing','Workspace integration','Meeting collaboration'],'Recording, meeting limits, and advanced features depend on account type.','https://workspace.google.com/products/meet/','#27845e','M','Software'),
make('discord','Discord','communication','Build community spaces with text channels, voice chat, and shared conversations.','Communities and groups centered on ongoing informal interaction.',['Community channels','Voice chat','Group messaging'],'Assess whether its community-oriented model meets your business governance needs.','https://discord.com/','#5865f2','D','Software'),
make('loom','Loom','communication','Record and share screen videos for asynchronous explanations and updates.','Distributed teams replacing some live meetings with recorded context.',['Screen recording','Video sharing','Asynchronous communication'],'Check recording limits, privacy controls, and workspace access before rollout.','https://www.loom.com/','#6655dc','L','Software'),
make('staragile','StarAgile','edtech','Explore professional training and certification-oriented courses across technology and management.','Learners seeking structured professional training and instructor-led options.',['Professional training','Certification-oriented courses','Technology and management topics'],'Confirm the current batch, trainer, total fees, exam inclusion, and refund terms.','https://staragile.com/','#d65d28','S','Learning platform'),
make('simplilearn','Simplilearn','edtech','Explore professional skills training and certification-oriented learning programs.','Professionals comparing structured learning programs for career development.',['Professional programs','Technology topics','Certification training'],'Delivery, certification outcomes, and support vary by the specific program.','https://www.simplilearn.com/','#e47721','S','Learning platform'),
make('coursera','Coursera','edtech','Learn through online courses, certificates, and degree programs from education partners.','Learners comparing institution-backed courses and flexible online study.',['Online courses','Professional certificates','Degree programs'],'Check program eligibility, assessment rules, and the credential actually awarded.','https://www.coursera.org/','#155bee','C','Learning platform'),
make('udemy','Udemy','edtech','Find instructor-created online courses across professional and personal skills.','Learners seeking flexible courses on a specific skill or topic.',['Online course marketplace','Self-paced learning','Broad topic coverage'],'Course quality and update frequency vary by instructor; review the syllabus carefully.','https://www.udemy.com/','#a13ce4','u','Learning platform'),
make('upgrad','upGrad','edtech','Explore online upskilling and education programs across career-focused subject areas.','Professionals evaluating longer education and upskilling pathways.',['Upskilling programs','Online education','Career-focused topics'],'Compare partner institution, entry requirements, total fees, and program support.','https://www.upgrad.com/','#d84441','u','Learning platform'),
make('edx','edX','edtech','Explore online courses, certificates, and degree pathways from education providers.','Learners seeking online study from institutional education partners.',['Online courses','Certificate programs','Degree pathways'],'Check course access terms, paid credential requirements, and assessment eligibility.','https://www.edx.org/','#193c53','e','Learning platform')
];
const categoryMap=new Map(categories.map(c=>[c.slug,c]));
export const categoryOf=(slug:string)=>categoryMap.get(slug)!;
export const tools:Tool[]=[...coreTools.map(t=>({...t,sourceChecked:(coreSourceDates as Record<string,string>)[t.slug]||null,sourceStatus:(coreSourceDates as Record<string,string>)[t.slug]?'Vendor source consulted':'Confirm directly with vendor'})),...expanded.tools].map(t=>({...t,categoryLabel:categoryOf(t.category)?.short||t.category}));
const toolMap=new Map(tools.map(t=>[t.slug,t]));
export const getTool=(slug:string)=>toolMap.get(slug);
export const categoryCounts:Record<string,number>=Object.fromEntries(categories.map(c=>[c.slug,0]));
for(const t of tools)categoryCounts[t.category]=(categoryCounts[t.category]||0)+1;
export const catalogueStats={tools:tools.length,categories:categories.length};
const coreGuides=[
{slug:'choosing-local-listings-software',category:'local-listings',title:'Choose local listings software by workflow, not directory count.',intro:'The right platform covers your important publishers and gives your team a reliable way to maintain accurate location data. Directory count alone does not establish coverage, update speed, or business value.',checks:['Create a list of priority maps, directories, and industry publishers for each market.','Run a pilot using a real location change, holiday hours, and a duplicate listing.','Confirm who owns business profiles and what access remains after cancellation.','Separate license fees, onboarding, citation services, and ongoing operational work.'],question:'Does a larger publisher network always mean better coverage?',answer:'No. Evaluate the publishers your customers use and the markets you operate in. Confirm eligibility for each location, update mechanisms, and exception handling rather than comparing headline counts.'},
{slug:'evaluating-ai-rfp-software',category:'rfp-software',title:'Test AI RFP software on a real response.',intro:'A useful RFP pilot tests answer accuracy, source traceability, permissions, review work, and export quality. Use the same questionnaire and knowledge sources across vendors so you can compare results fairly.',checks:['Include outdated documents and conflicting source statements in a controlled test.','Ask reviewers to track corrections, unsupported statements, and time spent.','Test access boundaries with content that only specific teammates may read.','Export the final response into the exact format your buyer requires.'],question:'Can an AI-generated response go straight to a customer?',answer:'Assign accountable reviewers before submission. Product claims, legal terms, security commitments, and customer-specific promises need human approval even when a draft includes supporting sources.'},
{slug:'choosing-team-communication-tools',category:'communication',title:'Choose a communication tool around how your team works.',intro:'Persistent chat, live meetings, and recorded updates solve different problems. Map the conversations your team needs before deciding whether to consolidate tools or keep a small complementary stack.',checks:['Separate urgent decisions, daily coordination, external meetings, and recorded walkthroughs.','Test guest invitations and access removal with an external collaborator.','Review retention, export, and administrative controls for the selected plan.','Compare the full cost across seats, meeting products, and paid add-ons.'],question:'Should every team use the same communication tool?',answer:'Shared standards help, but requirements vary. A customer-facing team may need dependable external meetings, while a distributed product team may benefit more from searchable chat and recorded explanations.'},
{slug:'comparing-professional-learning-platforms',category:'edtech',title:'Compare the course, not just the learning platform.',intro:'A platform name is only the starting point. The specific syllabus, trainer, delivery format, assessment, fees, and credential determine whether a course fits your learning goal.',checks:['Ask for the current syllabus and a clear breakdown of live, recorded, and project work.','Confirm the issuing body for any professional credential and its exam requirements.','Request total fees in writing, including exam vouchers, taxes, and optional services.','Read cancellation, batch-transfer, and support terms before enrolling.'],question:'Does placement assistance guarantee a job?',answer:'No. Assistance can include interview preparation, referrals, or access to opportunities. It should not be described as a job guarantee unless a specific enforceable agreement explicitly establishes that commitment.'}
];
export type Guide=(typeof coreGuides)[number]&{publishedAt?:string;updatedAt?:string};
export const guides:Guide[]=[...coreGuides,...additionalGuides];
export const latestGuides=guides.map((guide,index)=>({guide,index})).sort((a,b)=>(b.guide.publishedAt||'2026-10-05').localeCompare(a.guide.publishedAt||'2026-10-05')||b.index-a.index).map(x=>x.guide);
export const catalogueTotals={...catalogueStats,guides:guides.length};
export const pairs=[['chatgpt','claude'],['notion','obsidian'],['figma','canva'],['synup','yext'],['inventive-ai','loopio'],['slack','microsoft-teams'],['staragile','simplilearn']];
