import 'server-only';
import { authors } from './authors';
import { categories,tools } from './catalog';
import { contentPath,newContent,effectivePublished,scheduledTime,type CmsContent,type CmsKind,type CmsStore } from './cms-types';
import { contentAuthor,contentPages } from './content-index';
import { pageMarkdown } from './discovery';
const editable=['guide','tool','comparison','alternatives','answer','service','author'];
export function baseContent(path:string):CmsContent|undefined{const p=contentPages.find(p=>p.path===path);if(!p||!editable.includes(p.kind))return;const c={...newContent(p.kind as CmsKind),id:p.path,slug:p.path.split('/').at(-1)!,title:p.title,description:p.description,category:p.tool?.category||p.guide?.category||p.answer?.category||'ai',authorSlug:contentAuthor(p)?.slug||'yash',body:pageMarkdown(p).split('\n').filter(line=>!/^# |^Canonical: |^Author: |^Last modified: /.test(line)).join('\n').trim(),publishedAt:p.publishedAt?new Date(p.publishedAt).toISOString():undefined,updatedAt:p.updatedAt?new Date(p.updatedAt).toISOString():undefined};if(p.tool&&p.kind==='tool'){c.title=p.tool.name;c.tool={url:p.tool.url,fit:p.tool.fit,features:p.tool.features,caution:p.tool.caution,pricing:p.tool.pricing,pricingUrl:p.tool.pricingUrl||'',ai:Boolean(p.tool.ai),format:p.tool.format};c.tags=p.tool.keywords||'';}return c;}
export function adminData(store:CmsStore){const rows=new Map<string,{id:string;kind:string;title:string;slug:string;path:string;category:string;author:string;status:string;updatedAt:string;revision:number;hasDraft:boolean}>(contentPages.filter(p=>editable.includes(p.kind)).map(p=>[p.path,{id:p.path,kind:p.kind,title:p.kind==='tool'?p.tool!.name:p.title,slug:p.path.split('/').at(-1)!,path:p.path,category:p.tool?.category||p.guide?.category||p.answer?.category||'',author:contentAuthor(p)?.name||'TruTool',status:'published',updatedAt:p.updatedAt||p.publishedAt||'',revision:0,hasDraft:false}]));for(const r of store.records){const c=r.draft;rows.set(contentPath(c),{id:r.id,kind:c.kind,title:c.title,slug:c.slug,path:contentPath(c),category:c.category,author:authors.find(a=>a.slug===c.authorSlug)?.name||'TruTool',status:r.hidden?'unpublished':r.scheduled&&Date.parse(scheduledTime(r))>Date.now()?'scheduled':!r.published&&!r.scheduled?'draft':'published',updatedAt:r.updatedAt,revision:r.revision,hasDraft:JSON.stringify(r.draft)!==JSON.stringify(r.scheduled||r.published)});}const authorMap=new Map<string,{slug:string;name:string;focus:string}>(authors.map(a=>[a.slug,{slug:a.slug,name:a.name,focus:a.focus}]));for(const r of store.records){const a=effectivePublished(r);if(!r.hidden&&a?.kind==='author')authorMap.set(a.slug,{slug:a.slug,name:a.title,focus:a.description.slice(0,100)});}
 for(const r of store.records){const row=rows.get(contentPath(r.draft));if(row)row.author=authorMap.get(r.draft.authorSlug)?.name||'TruTool';}
 return {rows:[...rows.values()],activity:store.activity,revision:store.revision,categories:categories.map(c=>({slug:c.slug,name:c.name})),authors:[...authorMap.values()],tools:[...new Map([...tools.map(t=>[t.slug,{slug:t.slug,name:t.name,category:t.category}] as const),...store.records.flatMap(r=>{const c=effectivePublished(r);return c?.kind==='tool'?[[c.slug,{slug:c.slug,name:c.title,category:c.category}] as const]:[];})]).values()],storageReady:Boolean(process.env.BLOB_READ_WRITE_TOKEN||process.env.CMS_TEST_STORE),emailDeliveryReady:false,visibility:store.visibility||null};}
