import 'server-only';
import { authors } from './authors';
import { categories,SITE,tools,type Tool } from './catalog';
import { getPublished,hiddenPaths,isHidden } from './cms-store';
import { contentPath,type CmsContent } from './cms-types';
import { contentPages,type ContentPage } from './content-index';
import { pageMetadata } from './seo';
export async function publicContent(path:string){return (await getPublished()).find(c=>contentPath(c)===path);}
export { isHidden };
export function cmsTool(c:CmsContent):Tool{return {slug:c.slug,name:c.title,category:c.category,categoryLabel:categories.find(x=>x.slug===c.category)?.short||c.category,summary:c.description,fit:c.tool?.fit||'',features:c.tool?.features||[],caution:c.tool?.caution||'',url:c.tool?.url||c.sourceUrl,color:'#d6ef82',initial:c.title.slice(0,1),format:c.tool?.format||'Software',pricing:c.tool?.pricing||'Check current vendor pricing',pricingUrl:c.tool?.pricingUrl||undefined,keywords:c.tags,ai:c.tool?.ai,publishedAt:c.publishedAt,addedAt:c.publishedAt,updatedAt:c.updatedAt} as Tool;}
export async function publicTools(){const published=await getPublished(),map=new Map(tools.map(t=>[t.slug,t]));for(const c of published)if(c.kind==='tool')map.set(c.slug,cmsTool(c));const hidden=await hiddenPaths(),output:Tool[]=[];for(const t of map.values())if(!hidden.has('/tools/'+t.slug))output.push(t);return output;}
export function cmsPage(c:CmsContent):ContentPage{return {path:contentPath(c),title:c.title,description:c.description,kind:c.kind==='news'?'guide':c.kind,body:c.body,cms:c,publishedAt:c.publishedAt,updatedAt:c.updatedAt,...(c.kind==='tool'?{tool:cmsTool(c)}:{}),author:{...authors[0],slug:c.authorSlug,name:c.authorName||authors.find(a=>a.slug===c.authorSlug)?.name||'TruTool'}} as ContentPage;}
export async function publicPages(){const map=new Map(contentPages.map(p=>[p.path,p]));const all=await getPublished();for(const c of all){map.set(contentPath(c),cmsPage(c));if(c.kind==='tool'&&!map.has('/alternatives/'+c.slug))map.set('/alternatives/'+c.slug,{path:'/alternatives/'+c.slug,title:c.title+' Alternatives — Options to Compare',description:'Explore alternatives to '+c.title,kind:'alternatives',tool:cmsTool(c),publishedAt:c.publishedAt,updatedAt:c.updatedAt});}const hidden=await hiddenPaths(),output:ContentPage[]=[];for(const p of map.values())if(!hidden.has(p.path))output.push(p);return output;}
export function cmsMetadata(c:CmsContent){const image=c.image||SITE+'/api/og?path='+encodeURIComponent(contentPath(c))+'&v='+encodeURIComponent(c.updatedAt||c.publishedAt||'cms');const metadata=pageMetadata({title:c.metaTitle||c.title,description:c.metaDescription||c.description,alternates:{canonical:SITE+contentPath(c)},twitter:{card:'summary_large_image',title:c.metaTitle||c.title,description:c.metaDescription||c.description,images:[image]},authors:[{name:c.authorName||authors.find(a=>a.slug===c.authorSlug)?.name||'TruTool',url:SITE+'/authors/'+c.authorSlug}],openGraph:{title:c.metaTitle||c.title,description:c.metaDescription||c.description,type:c.kind==='author'?'profile':'article',images:[{url:image,alt:c.imageAlt||c.title}]}});return {...metadata,title:{absolute:c.metaTitle||c.title+' | TruTool'}};}

export function cmsSchema(c:CmsContent){const path=contentPath(c),url=SITE+path,author=authors.find(a=>a.slug===c.authorSlug),article=['guide','answer','news','comparison','alternatives','service'].includes(c.kind),node:Record<string,unknown>={'@type':article?'Article':c.kind==='author'?'ProfilePage':'WebPage','@id':url+'#content',url,name:c.title,description:c.description,isPartOf:{'@id':SITE+'/#website'},publisher:{'@id':SITE+'/#organization'},...(c.publishedAt?{datePublished:c.publishedAt}:{}),...(c.updatedAt?{dateModified:c.updatedAt}:{}),...(c.authorName||author?{author:{'@type':'Person',name:c.authorName||author?.name,url:SITE+'/authors/'+c.authorSlug}}:{})};if(article)Object.assign(node,{headline:c.title,mainEntityOfPage:url,...(c.image?{image:c.image}:{image:SITE+'/api/og?path='+encodeURIComponent(path)}),...(c.sourceUrl?{citation:[c.sourceUrl]}:{})});if(c.kind==='tool')node.mainEntity={'@type':'SoftwareApplication',name:c.title,url:c.tool?.url,description:c.description,applicationCategory:categories.find(x=>x.slug===c.category)?.name,featureList:c.tool?.features};if(c.kind==='author')node.mainEntity={'@type':'Person',name:c.title,url,description:c.description};return {'@context':'https://schema.org','@graph':[node,{'@type':'BreadcrumbList',itemListElement:[{'@type':'ListItem',position:1,name:'Home',item:SITE},{'@type':'ListItem',position:2,name:c.kind==='news'?'Everything AI':c.kind,item:SITE+(c.kind==='news'?'/everything-ai':path.split('/').slice(0,2).join('/'))},{'@type':'ListItem',position:3,name:c.title,item:url}]}]};}
export function cmsAuthorName(c:CmsContent){return c.authorName||authors.find(a=>a.slug===c.authorSlug)?.name||'TruTool';}
