export const diagnosticQuestions=[
{id:'stage',title:'Where is your product today?',options:[['early','Finding the first customers'],['growing','Growing a repeatable customer base'],['established','Expanding an established brand']]},
{id:'category',title:'Which world does your product belong to?',options:[['local-listings','Local marketing and business listings'],['rfp-software','RFP responses and proposal software'],['communication','Team communication'],['edtech','Professional learning'],['other','Another software category']]},
{id:'goal',title:'What should improve first?',options:[['discovery','More relevant people discovering us'],['comparison','A clearer case when buyers compare options'],['citations','Visibility in search and AI answers'],['conversion','More enquiries from existing traffic']]},
{id:'foundation',title:'What does your content foundation look like?',options:[['starting','Mostly a homepage and product pages'],['developing','Some guides, comparisons, and case studies'],['mature','An established library with measurement']]},
{id:'capacity',title:'How much publishing capacity do you have?',options:[['solo','One person or a small part-time team'],['team','A team that can publish regularly'],['supported','Writers and subject experts working together']]}
];
export function diagnosticResult(a:Record<string,string>){
const paths:Record<string,{title:string;reason:string;steps:string[]}>= {
 discovery:{title:'Build a focused discovery cluster.',reason:'Your priority is reaching relevant buyers. Start with a small connected set of pages around the work your product solves.',steps:['Define the buyer, use case, and category in plain language.','Publish a useful category guide and a complete product profile.','Link supporting answers to the category and product pages.']},
 comparison:{title:'Make comparison research easier.',reason:'Your priority is helping buyers understand the trade-offs. Build fair, evidence-backed comparisons around real purchase decisions.',steps:['Use the same fit, capabilities, limitations, and pricing fields for every option.','Explain which requirements should rule an option in or out.','Support important claims with current official sources and dated evaluation notes.']},
 citations:{title:'Strengthen your retrieval foundation.',reason:'Your priority is discovery in search and AI answers. Make your content accessible, specific, sourced, and easy to interpret.',steps:['Check indexability, canonical URLs, and crawl access for priority pages.','Answer buyer questions directly and use consistent product and category names.','Add visible sources, update dates, authorship, and accurate structured data.']},
 conversion:{title:'Clarify the next decision.',reason:'Your priority is turning existing interest into relevant enquiries. Reduce uncertainty between reading about a product and evaluating it.',steps:['Put buyer fit, limitations, and the next action on the same page.','Make trial, pricing, and enquiry paths clear and easy to use.','Track qualified enquiries by landing page and improve the pages buyers already visit.']}
};
const result=paths[a.goal]||paths.discovery;
const pace=a.capacity==='solo'?'Start with one priority page and one supporting answer per publishing cycle.':a.capacity==='team'?'Build one category cluster, with a product profile, buying guide, comparison, and supporting answers.':'Combine subject-expert review with a small repeatable publishing and measurement programme.';
const foundation=a.foundation==='starting'?'First make the main product and category pages accurate and complete.':a.foundation==='developing'?'Audit and connect the content you already have before creating more pages.':'Use search performance and enquiry data to identify gaps and refresh the pages that matter most.';
const stage=a.stage==='early'?'Prioritise learning which buyers and use cases respond before expanding the content programme.':a.stage==='growing'?'Keep the programme tied to the use cases that already produce qualified interest.':'Separate the needs of new markets or segments, and measure each cluster against its own baseline.';
return {...result,pace,foundation,stage};
}
