import {tools,categories,type Tool} from './catalog';
export const discoveryQueries=['AI research assistants','Meeting notes','Remove image backgrounds','Project management','No-code app builders','SEO tools','Local listings management','RFP response software'];
const normalize=(s:string)=>s.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9\s]/g,' ').replace(/\s+/g,' ').trim();
const aliases:Record<string,string>={ai:'artificial intelligence assistant generative chatbot llm',productivity:'notes note tasks todo focus organisation planning pkm knowledge',design:'graphics graphic logo logos illustration vector ui ux prototype mockup creative',marketing:'campaign campaigns audience automation engagement',seo:'search engine optimization optimisation keyword keywords backlink backlinks rankings audit',crm:'contacts contact customer relationship pipeline leads',sales:'prospecting prospect leads lead outbound outreach cold email enrichment',automation:'automate automated workflow workflows integrate integration agent agents',support:'helpdesk help desk tickets customer service chatbot',email:'newsletter newsletters inbox mail emailing smtp',forms:'form questionnaire questionnaires collect responses',scheduling:'calendar calendars book booking appointment appointments availability',research:'papers paper scientific literature citations references study academic',finance:'expense expenses spend spending budget budgets banking',accounting:'invoice invoices invoicing bookkeeping tax accounts',payments:'payment billing subscription subscriptions checkout',ecommerce:'e commerce shop store storefront selling products',hr:'human resources payroll workforce employee employees people management',recruiting:'recruitment recruit hiring candidates applicant interview talent jobs',legal:'contracts contract signature esign signing compliance privacy governance',video:'videos editing edit clips recording screen screenrecording subtitle captions avatars',audio:'voice voices sound music speech transcription tts transcribe podcast podcasts',security:'cybersecurity cybersecurity vulnerabilities vpn threats protection',passwords:'password credentials authentication identity sso login auth',database:'databases sql postgres postgresql mongodb data storage redis',cloud:'hosting server servers infrastructure compute deployment',developer:'developers coding code programming api apis git software engineering',testing:'tests test qa quality automation browser browsers',analytics:'analysis reports reporting metrics dashboard dashboards statistics stats tracking',localisation:'translation translate languages multilingual localization',edtech:'education learning course courses certification certificate pmp cspo safe agile training learn',local:'listings listing citation citations maps locations location reputation reviews google business profile gmb gbp',rfp:'rfps proposal proposals questionnaire ddq rfi response bid bidding tender'};
const categoryText=new Map(categories.map(c=>[c.slug,normalize(c.name+' '+c.short+' '+c.description+' '+Object.entries(aliases).filter(([k])=>normalize(c.name+' '+c.slug).includes(k)).map(([,v])=>v).join(' '))]));
const index=tools.map(tool=>({tool,name:normalize(tool.name),compact:normalize(tool.name).replace(/ /g,''),text:normalize([tool.name,tool.summary,tool.fit,...tool.features,tool.keywords||'',categoryText.get(tool.category)].join(' '))}));
const stop=new Set('a an the for of to with in on by best top software tool tools app apps platform platforms free paid cheap affordable help need want me my our find compare alternative alternatives how can i use'.split(' '));
function distance(a:string,b:string){if(Math.abs(a.length-b.length)>2)return 3;let row=Array.from({length:b.length+1},(_,i)=>i);for(let i=1;i<=a.length;i++){const next=[i];for(let j=1;j<=b.length;j++)next[j]=Math.min(next[j-1]+1,row[j]+1,row[j-1]+(a[i-1]===b[j-1]?0:1));row=next;}return row[b.length];}
function stem(s:string){return s.length>5?s.replace(/(ing|ers|ies|s)$/,''):s;}
export function searchTools(query:string,category='',sort='relevance'):Tool[]{
 const q=normalize(query),compact=q.replace(/ /g,''),terms=q.split(' ').filter(x=>x&&!stop.has(x));
 const related=Object.entries(aliases).filter(([key,value])=>terms.some(t=>key===t||value.split(' ').includes(t))).map(([key,value])=>[key,...value.split(' ')]);
 const scores=index.filter(x=>!category||x.tool.category===category).map(x=>{
  if(!q||!terms.length)return {tool:x.tool,score:1};
  let score=x.compact===compact?1000:x.name===q?900:x.compact.startsWith(compact)?160:x.name.includes(q)?130:0;
  let matches=0;for(const term of terms){if(x.text.includes(term)||x.text.includes(stem(term))){matches++;score+=x.name.includes(term)?25:6;}}
  if(matches===terms.length)score+=25;
  for(const group of related)if(group.some(word=>x.text.includes(word)))score+=3;
  if(score===0&&compact.length>=4&&(distance(compact,x.compact)<=2||x.name.split(' ').some(n=>distance(compact,n)<=1)))score=55;
  return {tool:x.tool,score:matches||score>=55?score:related.length&&score>=3?score:0};
 }).filter(x=>x.score>0);
 scores.sort((a,b)=>sort==='az'?a.tool.name.localeCompare(b.tool.name):b.score-a.score||a.tool.name.localeCompare(b.tool.name));
 return scores.map(x=>x.tool);
}
export const categoryCounts=Object.fromEntries(categories.map(c=>[c.slug,tools.filter(t=>t.category===c.slug).length]));
