export const serviceCategories=[
{slug:'cloud-consulting',name:'Cloud & ecosystem consulting',description:'Implementation, migration, and platform integration.',providers:[['Accenture','https://www.accenture.com'],['Deloitte','https://www.deloitte.com'],['IBM Consulting','https://www.ibm.com/consulting'],['Slalom','https://www.slalom.com'],['Thoughtworks','https://www.thoughtworks.com']]},
{slug:'marketing-services',name:'Marketing & content services',description:'Content, search, campaigns, and audience development.',providers:[['Directive','https://directiveconsulting.com'],['Siege Media','https://www.siegemedia.com'],['Animalz','https://www.animalz.co'],['Omniscient Digital','https://beomniscient.com'],['WebFX','https://www.webfx.com']]},
{slug:'design-services',name:'Design & product services',description:'Product strategy, research, design, and creative delivery.',providers:[['IDEO','https://www.ideo.com'],['ustwo','https://ustwo.com'],['frog','https://www.frog.co'],['Work & Co','https://work.co'],['Designit','https://www.designit.com']]},
{slug:'software-development',name:'Software & engineering services',description:'Custom software, engineering, and technology delivery.',providers:[['EPAM','https://www.epam.com'],['Globant','https://www.globant.com'],['Endava','https://www.endava.com'],['TCS','https://www.tcs.com'],['Infosys','https://www.infosys.com']]},
{slug:'security-services',name:'Security & privacy services',description:'Security assessment, incident response, and risk work.',providers:[['Mandiant','https://cloud.google.com/security/products/mandiant'],['NCC Group','https://www.nccgroup.com'],['Bishop Fox','https://bishopfox.com'],['HackerOne','https://www.hackerone.com'],['Trail of Bits','https://www.trailofbits.com']]},
{slug:'translation-services',name:'Translation & localisation services',description:'Translation, localisation, and multilingual delivery.',providers:[['TransPerfect','https://www.transperfect.com'],['RWS','https://www.rws.com'],['LanguageLine','https://www.languageline.com'],['Smartling','https://www.smartling.com'],['Welocalize','https://www.welocalize.com']]},
{slug:'staffing-services',name:'Staffing & recruiting services',description:'Recruiting, contract talent, and workforce support.',providers:[['Randstad','https://www.randstad.com'],['Adecco','https://www.adecco.com'],['Robert Half','https://www.roberthalf.com'],['Hays','https://www.hays.com'],['Toptal','https://www.toptal.com']]},
{slug:'business-services',name:'Business & operations services',description:'Business consulting, finance operations, and transformation.',providers:[['PwC','https://www.pwc.com'],['EY','https://www.ey.com'],['KPMG','https://kpmg.com'],['Bain & Company','https://www.bain.com'],['BCG','https://www.bcg.com']]}
];
