import { CmsArticle } from '@/components/cms-article';
import { PageStructuredData } from '@/components/page-structured-data';
import Link from '@/components/site-link';
import { ToolCard } from '@/components/tool-card';
import { categoryOf,SITE,tools } from '@/lib/catalog';
import { cmsMetadata,isHidden,publicContent,publicTools } from '@/lib/cms-public';
import { pageMetadata } from '@/lib/seo';
import { notFound } from 'next/navigation';
export const revalidate=30;
export function generateStaticParams(){return tools.map(t=>({slug:t.slug}))}
export async function generateMetadata({params}:{params:Promise<{slug:string}>}){const {slug}=await params;const cmsPath='/alternatives/'+slug,cms=await publicContent(cmsPath);if(await isHidden(cmsPath))notFound();if(cms)return cmsMetadata(cms);const t=(await publicTools()).find(t=>t.slug===slug);return t?pageMetadata({title:t.name+' Alternatives — Options to Compare',description:'Explore '+categoryOf(t.category).name.toLowerCase()+' alternatives to '+t.name+' by fit, capabilities, and trade-offs.',alternates:{canonical:SITE+'/alternatives/'+slug}}):{title:'Not found'}}
export default async function Page({params}:{params:Promise<{slug:string}>}){const {slug}=await params;const cmsPath='/alternatives/'+slug,cms=await publicContent(cmsPath);if(await isHidden(cmsPath))notFound();if(cms)return <CmsArticle content={cms}/>;const t=(await publicTools()).find(t=>t.slug===slug);if(!t)notFound();const c=categoryOf(t.category),others=(await publicTools()).filter(x=>x.category===t.category&&x.slug!==t.slug);return <main id="main" className="shell"><PageStructuredData path={'/alternatives/'+slug}/><div className="page-intro"><div className="breadcrumb"><Link href="/alternatives">Alternatives</Link><span>/</span><span>{t.name}</span></div><span className="eyebrow">SAME-CATEGORY OPTIONS</span><h1>{t.name} alternatives</h1><p>Other {c.name.toLowerCase()} platforms include {others.slice(0,6).map(t=>t.name).join(', ')}. They share a category, but their workflows, coverage, and terms can differ. These are options to evaluate, not ranked recommendations.</p></div><div className="page-body"><div className="tools-grid">{others.map(x=><div key={x.slug}><ToolCard tool={x}/><Link className="text-link" style={{display:'block',margin:'14px 0 20px'}} href={'/compare/'+t.slug+'-vs-'+x.slug}>Compare {t.name} with {x.name}</Link></div>)}</div><section className="answer-block"><h2>How should you evaluate a switch?</h2><p>{c.answer} Include migration work, access, and cancellation terms in the evaluation. A shared category does not make two products direct substitutes.</p></section><Link className="text-link" href={'/tools/'+t.slug}>Return to {t.name} profile</Link></div></main>}
