import {PageStructuredData} from '@/components/page-structured-data';
import {pageMetadata} from '@/lib/seo';
import {ProviderLogo} from '@/components/provider-logo';
import Link from '@/components/site-link';
import {notFound} from 'next/navigation';
import {serviceCategories} from '@/lib/services';
import {SITE} from '@/lib/catalog';
export function generateStaticParams(){return serviceCategories.map(c=>({slug:c.slug}))}
export async function generateMetadata({params}:{params:Promise<{slug:string}>}){const {slug}=await params,c=serviceCategories.find(c=>c.slug===slug);return c?pageMetadata({title:c.name+' — Providers & Evaluation',description:c.description+' Compare scope, delivery, and provider fit.',alternates:{canonical:SITE+'/services/'+slug}}):{title:'Service not found'}}
export default async function Page({params}:{params:Promise<{slug:string}>}){const {slug}=await params,c=serviceCategories.find(c=>c.slug===slug);if(!c)notFound();return <main id="main" className="shell"><PageStructuredData path={'/services/'+slug}/><div className="page-intro"><div className="breadcrumb"><Link href="/services">Services</Link><span>/</span><span>{c.name}</span></div><span className="eyebrow">FIND THE RIGHT ENGAGEMENT</span><h1>{c.name}</h1><p>{c.description} Start with your requirements, then ask each provider about relevant work, scope, and delivery.</p></div><div className="service-provider-grid page-body">{c.providers.map(([name,url])=><article className="service-provider-card" key={name}><span className="eyebrow">PROVIDER TO EXPLORE</span><div className="provider-heading"><ProviderLogo name={name} url={url}/><h2>{name}</h2></div><p>Review the provider’s current services, locations, and engagement options directly. Ask for examples that match your requirements.</p><a className="button dark" href={url} target="_blank" rel="noopener noreferrer">Visit {name}</a></article>)}</div><section className="answer-block"><h2>Questions to ask before you start</h2><ul><li>What is included in the scope, and what is explicitly outside it?</li><li>Who owns the accounts, data, source files, and final deliverables?</li><li>What access is required, and how will it be removed at handover?</li><li>What are the milestones, acceptance criteria, and total costs?</li><li>Who will do the work, and how will progress and issues be reported?</li></ul><p>These are discovery listings, not customer ratings or endorsements. Confirm current offerings with the provider.</p></section><Link className="text-link" href="/services">Explore another service</Link></main>}
