/* eslint-disable @next/next/no-img-element */
import sharp from 'sharp';
import {ImageResponse} from 'next/og';
import {readFile} from 'node:fs/promises';
import path from 'node:path';
import {getTool,categories,guides,tools} from '@/lib/catalog';
import {getCommunityAnswer} from '@/lib/community-answers';
import {serviceCategories} from '@/lib/services';
import {brandAssets} from '@/lib/brand-assets';
import {coverFor} from '@/components/guide-card';
// Node allows local, bundled artwork; generating previews makes no remote requests.
export const runtime='nodejs';
const pageTitles:Record<string,string>={'/':'Find the tools. Make your next move.','/tools':'Discover your next tool.','/categories':'Every kind of work. One directory.','/guides':'Buy smarter. Start with the work.','/compare':'Your tools. Compared.','/alternatives':'Explore a different way to work.','/community':'Good tools. Better conversations.','/services':'Find expertise. Move the work forward.','/diagnostic':'Find your fit. Build your pilot.','/about':'A clearer point of view.','/contact':'Start a conversation.','/editorial-policy':'Useful research. Clearer choices.','/methodology':'How TruTool researches tools.','/sources':'Sources & brand credits.','/privacy':'Your privacy on TruTool.','/terms':'Terms of use.','/cookies':'Browser storage & cookies.','/authors/yash':'Meet Yash. Read the field guides.','/list-your-product':'Put your product on the radar.'};
async function artwork(src:string){try{const safe=path.join(process.cwd(),'public',src);let bytes=await readFile(safe),ext=path.extname(src);if(ext==='.webp'){bytes=await sharp(bytes).resize(600,600,{fit:'inside',withoutEnlargement:true}).png().toBuffer();ext='.png'}return 'data:'+({'.svg':'image/svg+xml','.png':'image/png','.webp':'image/webp'}[ext]||'image/jpeg')+';base64,'+bytes.toString('base64')}catch{return null}}
export async function GET(request:Request){
 const pathname=new URL(request.url).searchParams.get('path')||'/';
 if(pathname.length>240)return new Response(null,{status:400});
 if(!pathname.startsWith('/')||pathname.startsWith('//'))return new Response(null,{status:400});
 const parsed=new URL(pathname,'https://trutool-directory.vercel.app');
 const parts=parsed.pathname.split('/').filter(Boolean),tool=['tools','alternatives'].includes(parts[0])?getTool(parts[1]):null,guide=parts[0]==='guides'?guides.find(g=>g.slug===parts[1]):null,category=parts[0]==='categories'?categories.find(c=>c.slug===parts[1]):null,service=parts[0]==='services'?serviceCategories.find(c=>c.slug===parts[1]):null,pair=parts[0]==='compare'?(parts[1]?parts[1].split('-vs-'):(parsed.searchParams.get('tools')||'').split(',')).map(getTool).filter((t):t is NonNullable<typeof t>=>Boolean(t)).slice(0,3):[];
 const answer=parts[0]==='community'?getCommunityAnswer(parts[1]):null;
 let title=pageTitles[parsed.pathname],label='THE DIRECTORY FOR YOUR NEXT MOVE',imageSrc:string|undefined=parsed.pathname==='/'?coverFor('ai'):undefined,logos:string[]=[],subtitle='Clearer choices. Better tools.';
 if(tool){title=tool.name+(parts[0]==='alternatives'?' alternatives':'');label='FEATURES · FIT · PRICING · REVIEWS';subtitle=tool.summary;imageSrc=coverFor(tool.category);logos=[brandAssets[tool.slug]].filter(Boolean)}
 if(guide){title=guide.title;label='THE TRUTOOL FIELD GUIDE';subtitle=guide.intro;imageSrc=coverFor(guide.category)}
 if(category){title=category.name;label='EXPLORE THE CATEGORY';subtitle=category.description;imageSrc=coverFor(category.slug)}
 if(service){title=service.name;label='SERVICES DIRECTORY';subtitle=service.description}
 if(pair.length>=2&&new Set(pair.map(t=>t.slug)).size===pair.length){title=pair.map(t=>t.name).join(' vs ');label='YOUR TOOLS. SIDE BY SIDE.';subtitle='Compare fit, capabilities, trade-offs, and pricing.';logos=pair.map(t=>brandAssets[t.slug]).filter(Boolean)}
 if(answer){title=answer.question;label='COMMUNITY · THE PRACTICAL ANSWER';subtitle=answer.answer;imageSrc=coverFor(answer.category);logos=answer.toolSlugs.slice(0,2).map(slug=>brandAssets[slug]).filter(Boolean)}
 if(!title)return new Response(null,{status:404});
 const previewLimit=answer?130:185,subtitlePreview=subtitle.length>previewLimit?subtitle.slice(0,previewLimit).replace(/\s+\S*$/,'')+'…':subtitle;
 const [brand,cover,...marks]=await Promise.all([artwork('/trutool-logo.png'),imageSrc?artwork(imageSrc):null,...logos.map(artwork)]);
 const response=new ImageResponse(<div style={{display:'flex',width:'100%',height:'100%',background:'#142333',color:'#fff',padding:56,position:'relative',overflow:'hidden',fontFamily:'sans-serif'}}><div style={{display:'flex',position:'absolute',width:520,height:520,borderRadius:260,background:'#263c3b',right:-160,top:-100}}/><div style={{display:'flex',position:'absolute',width:440,height:440,borderRadius:220,border:'1px solid #486055',right:-120,bottom:-220}}/><div style={{display:'flex',flexDirection:'column',justifyContent:'space-between',width:cover?'68%':'100%'}}><div style={{display:'flex',alignItems:'center',gap:20}}><div style={{display:'flex',background:'#fff',borderRadius:18,width:206,height:87,alignItems:'center',justifyContent:'center'}}>{brand?<img src={brand} width={192} height={81} alt="TruTool"/>:<span style={{color:'#142333',fontSize:36}}>TruTool</span>}</div><span style={{fontSize:18,color:'#c7e99a'}}>Clearer choices. Better tools.</span></div><div style={{display:'flex',flexDirection:'column',gap:answer?14:22}}><span style={{fontSize:16,color:'#caee94',letterSpacing:3}}>{label}</span>{marks.length>0&&<div style={{display:'flex',gap:14}}>{marks.map((src,i)=>src?<div key={i} style={{display:'flex',width:answer?52:70,height:answer?52:70,background:'#fff',padding:answer?9:12,borderRadius:answer?12:16}}><img src={src} width={answer?34:46} height={answer?34:46} alt=""/></div>:null)}</div>}<div style={{display:'flex',fontSize:answer?(title.length>85?40:46):(title.length>60?46:62),fontWeight:700,lineHeight:1.12,letterSpacing:-2,maxWidth:cover?690:1000}}>{title}</div><div style={{display:'flex',fontSize:answer?18:22,color:'#c5d3d9',lineHeight:1.4,maxWidth:cover?650:960}}>{subtitlePreview}</div></div><div style={{display:'flex',alignItems:'center',justifyContent:'space-between',marginTop:24,fontSize:17,color:'#b4c4ca'}}><span>trutool-directory.vercel.app</span><span style={{color:'#c7e99a'}}>{tools.length} tools · {categories.length} categories</span></div></div>{cover&&<div style={{display:'flex',position:'absolute',right:44,top:160,width:300,height:360,overflow:'hidden',borderRadius:28,border:'1px solid #587069'}}><img src={cover} width={300} height={360} alt="" style={{objectFit:'cover'}}/></div>}</div>,{width:1200,height:630,headers:{'Cache-Control':'public, max-age=86400, s-maxage=86400, stale-while-revalidate=604800'}});
 return new Response(await response.arrayBuffer(),{headers:response.headers});
}
